#!/usr/bin/env bash

set -x

bin/build

docker-compose up -d

docker-compose exec rails bash -l -c 'bundle exec rake db:reset'

wget -O - --retry-connrefused -T 60 http://${HOST:-localhost}:8080/
status=$?

docker-compose logs

docker-compose rm -sfv

exit $status
