sudo: required
services:
  - docker
script:
  - test/run
after_success:
  - if [ "$TRAVIS_BRANCH" == 'master' -a "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push opensnp/rails;
      docker push opensnp/rails-sidekiq;
    fi
